name: Deploy Project
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: set git credentials
        run: | 
            git config --global user.email "anushapalle11@gmail.com"
            git config --global user.name "AnushaPalle"
      - name: Deploy
        run: npm run deploy
  
  